jwt:
  header: Authorization
  secret: petra
  expiration: 2629800000


spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://192.168.0.88/petri_constructor?useUnicode=yes&characterEncoding=UTF8
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql



logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        tool:
          schema: DEBUG



server:
  servlet:
    session:
      cookie:
        path: /
