spring:
  datasource:
    url: jdbc:postgresql:${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
  sql:
    init:
      mode: always

jwt:
  header: Authorization
  secret: ${jwtSecret}
  expiration: 2629800000


logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        tool:
          schema: DEBUG



server:
  servlet:
    session:
      cookie:
        path: /
